### PR TITLE
Fix: Convenience DID constructor

### LINKED ISSUE #35: Fix Did constructor
The convenience constructor of class _org.eclipse.tractusx.ssi.lib.model.did.Did_ returns an uninitialized object. Instead of 
```java
new Did(method, didMethodIdentifier, null);
``` 
it should call the other constructor
```java
this(method, didMethodIdentifier, null);
```

### PR DESCRIPTION
**Pull request by bjoern-arnold**
## Description

Fixes #35.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by DominikPinsel — APPROVED** [review]
@borisrizov-zf Can we merge this? :)

**Comment by borisrizov-zf** [comment]
@bjoern-arnold Hi, we're finally up-to-speed with releases, etc. Can you **rebase** your branch, so you get all of the recent updates and then we can merge.

**Comment by borisrizov-zf** [comment]
@bjoern-arnold ping to **rebase**.

**Comment by bjoern-arnold** [comment]
@borisrizov-zf Done

**Comment by borisrizov-zf** [comment]
@bjoern-arnold Hi, please **rebase** and not **merge**. You can run the following to fix this.

```bash
git checkout pr/35-fix-did-constructor
git reset --hard 0ce1d9a
git remote add upstream git@github.com:eclipse-tractusx/SSI-agent-lib.git
git fetch upstream
git rebase upstream/main
git push -f
```

**Comment by bjoern-arnold** [comment]
@borisrizov-zf ok, should be done now.

**Comment by borisrizov-zf** [comment]
@bjoern-arnold Sorry, your commit history has two Merge commits, which are not necessary. Please fix this.

**Comment by bjoern-arnold** [comment]
@borisrizov-zf  ok, I got rid of the superfluous merge commits

**Pull request merged**
