### PR TITLE
Fix: Excluded conflicting dependency in pom.xml

### LINKED ISSUE #37: Exclude conflicting version of "titanium-json-ld"
The libraries 
* com.apicatalog:titanium-json-ld-jre8:1.3.1
* com.apicatalog:titanium-json-ld:1.3.2
include the same classes but have different artifacts identifiers which prevents the package manager to resolve the conflict automatically.

Since this causes class resolution conflicts, the dependency imported transitively by **rdf-urdna** should be excluded manually.

### PR DESCRIPTION
**Pull request by bjoern-arnold**
## Description
Fixes #37 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by DominikPinsel — APPROVED** [review]
@borisrizov-zf Can we merge this? :)

**Comment by borisrizov-zf** [comment]
@bjoern-arnold Hi, I think we can follow the previous PR with this one. I'll ping you for a rebase. Just be prepared :)

**Comment by borisrizov-zf** [comment]
@bjoern-arnold Hi, you can rebase + force push, then we can merge this.

**Comment by bjoern-arnold** [comment]
Hi @borisrizov-zf,
I made a mistake and removed the original commit. Do I have to make a new PR or can you reopen this one?

**Comment by borisrizov-zf** [comment]
I can re-open, no problem

**Pull request merged**
