### PR TITLE
Chore: migrate old (catenax-ng) repo

### PR DESCRIPTION
**Pull request by borisrizov-zf**
## Description

This is a MIGRATION of the old repository into tractus-x. The code changes are already included in the current release of the MIW.
Files updated during this PR:
build.yaml - Workflow file for building the project, has been updated to reflect the project structure and to run correctly
DEPENDENCIES - A fresh run of the dash-license tool has been executed
Various java-files with missing license header have been update to include it - no code changes there.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ x ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ x ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by borisrizov-zf** [comment]
@SebastianBezold hi, this PR is the migration of the old repo, as we discussed during the previous release. I've also added the missing license header to all files in the repo and I've updated the DEPENDENCIES. This is a large PR, but afterwards we can migrate the MIW settings to use this repo and make the necessary changes to emit a maven artefact.

**Comment by borisrizov-zf** [comment]
@the-tatanka hi, can you please take a look. I think Sebastian Bezold is not available. We need to review this PR, so we can update the dependency in MIW. We also need this version of the code in tractus-x so we can deploy the artefact to maven. This as all a condition in order for us to release the MIW in 3.2

**Comment by the-tatanka** [comment]
Hi @borisrizov-zf , I am completely useless as far as the license stuff is concerned.
I would advise you to contact someone from the system team.
Sorry @carslen  for recommending you again, can you possibly help out?

**Comment by the-tatanka** [comment]
I appreciate the update of the dependencies in your pom.xml file

**Comment by borisrizov-zf** [comment]
> Hi @borisrizov-zf , I am completely useless as far as the license stuff is concerned.
> I would advise you to contact someone from the system team.
> Sorry @carslen for recommending you again, can you possibly help out?

This was already reviewed as we did the Release for the MIW. These are the changes up to that point, merged into this repo. Maybe @SebastianBezold is back and can review?

**Comment by scherersebastian** [comment]
@SebastianBezold is out for 5 weeks :(

**Comment by borisrizov-zf** [comment]
@scherersebastian oh that's too long. Can we ask someone else to take a look? Otherwise we'll have to keep the remote SSI lib and do the merge afterwards. We already have some fixes which need to be pushed.

**Comment by SebastianBezold** [comment]
> @scherersebastian oh that's too long. Can we ask someone else to take a look? Otherwise we'll have to keep the remote SSI lib and do the merge afterwards. We already have some fixes which need to be pushed.

Please just use our community communication channels and ask for a review on chat or mailing list briefly describing what this is about

**Comment by carslen** [comment]
Create IP Check at Eclipse Foundation: [#10664](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10664)

**Comment by borisrizov-zf** [comment]
@carslen are there any updates from the IP team? I didn't see anything in the issue, but maybe you heard something.

**Comment by carslen** [comment]
IP check approved and closed by EF.

**Comment by carslen** [comment]
Can one of the Devs please approve the PR from a technical perspective? I'll merge the PR afterwards.

**Comment by borisrizov-zf** [comment]
> Can one of the Devs please approve the PR from a technical perspective? I'll merge the PR afterwards.

I'll add Koptan as a reviewer, he's the author and owner on the catenax-ng side.

@koptan please review.

**Comment by koptan** [comment]
@carslen, please go a head.

**Comment by borisrizov-zf** [comment]
ping @carslen

**Comment by carslen** [comment]
I'll merge it now, but next time, please do a GH review of the PR instead and approve.

**Pull request merged**
