### PR TITLE
Add test case for manipulated ProofOptions

### PR DESCRIPTION
**Pull request by matgnt**
The 'verify' should fail in such cases

Adds a test case for #34
Without any additional changes, this test case will fail for now.

### CODE REVIEW

**Comment by borisrizov-zf** [comment]
Hi @matgnt,

thank you for your contribution. Can you please reformat using `mvn spotless:apply`. I'll ping you when we want to rebase the PR for a final merge.

**Comment by matgnt** [comment]
I'm not a Java Expert :-)
In my environment I'm getting an error running the suggested command. Even on `main`
```
./mvnw clean spotless:apply
...
[INFO] --- spotless-maven-plugin:2.28.0:apply (default-cli) @ cx-ssi-lib ---
[ERROR] Step 'google-java-format' found problem in 'src/main/java/org/eclipse/tractusx/ssi/lib/validation/JsonLdValidatorImpl.java':
null
java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:118)
```

**Comment by koptan** [comment]
I will take care of it, no worries @matgnt. Thanks a lot.

**Comment by borisrizov-zf** [comment]
@matgnt just letting you know that we're resolving an issue with the publish pipeline. After that the PR can be merged normally. Hang on tight ;)

**Comment by matgnt** [comment]
No worries, this is just a test case for #34 
Beware, that it will fail for now! You may also decide to merge it later, once a fix is available - or as part of the fix...

Matthias

**Comment by koptan** [comment]
> No worries, this is just a test case for #34 Beware, that it will fail for now! You may also decide to merge it later, once a fix is available - or as part of the fix...
> 
> Matthias

@borisrizov-zf I am working on it, please wait until we have a fix.

**Comment by koptan** [comment]
@borisrizov-zf, this PR can be closed, I have added it this test case in #77, because the Fix and Test case should go together.

**Comment by borisrizov-zf** [comment]
Closing in favour of #77\

**Pull request closed without merging**
