### PR TITLE
fix: correcting typo Invalid in code

### LINKED ISSUE #20: Improvement: Invalid has a typo
Numerous class names and methods are written as `Invalide` which should be fixed.

### PR DESCRIPTION
**Pull request by koptan**
## Description

Correcting all the "**Invalide**" words to the correct one "**Invalid**"

Closes #20

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by koptan** [comment]
@borisrizov-zf, build task is taking too much time, could please check what is the issue?

**Comment by borisrizov-zf** [comment]
It seems that Fraunhofer was down for a while. We'll have to check that again, before merging.

**Review by borisrizov-zf — APPROVED** [review]

**Comment by florianrusch-zf** [comment]
@koptan could you please fix the merge configs ;-)

**Comment by borisrizov-zf** [comment]
I think if you rebase, it'll all be fixed.

**Review by DominikPinsel — APPROVED** [review]

**Comment by koptan** [comment]
I will close this PR in favor of #44 .

**Pull request closed without merging**
