### PR TITLE
fix: credentialStatus id missing

### PR DESCRIPTION
**Pull request by nitin-vavdiya**
Fix for: https://github.com/eclipse-tractusx/SSI-agent-lib/issues/70

### CODE REVIEW

**Review by DominikPinsel — APPROVED** [review]

**Comment by borisrizov-zf** [comment]
@nitin-vavdiya please rebase as we've merge big changes into 'main'.

**Comment by nitin-vavdiya** [comment]
rebase done

**Comment by borisrizov-zf** [comment]
@nitin-vavdiya maybe you forgot to force push, the branch is not rebased and includes existing changes.

**Comment by nitin-vavdiya** [comment]
> @nitin-vavdiya maybe you forgot to force push, the branch is not rebased and includes existing changes.

Let me create a new branch from the main branch as the changes are very small and this will be faster.

Closing this PR

**Comment by nitin-vavdiya** [comment]
> > @nitin-vavdiya maybe you forgot to force push, the branch is not rebased and includes existing changes.
> 
> Let me create a new branch from the main branch as the changes are very small and this will be faster.
> 
> Closing this PR

New PR: https://github.com/eclipse-tractusx/SSI-agent-lib/pull/90

**Pull request closed without merging**
